"""Migration for creating client model in database."""

# Generated by Django 2.2.6 on 2019-10-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """Map all model fields to database table attributes."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(choices=[('M', 'Male'),
                                                     ('F', 'Female'),
                                                     ('Ot', 'Other')],
                                            max_length=1)),
                ('address', models.TextField(max_length=500)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
