"""Auto generated migrations."""

# Generated by Django 2.2.6 on 2019-10-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration function."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
