"""Auto generated migrations for default addition in age."""

# Generated by Django 2.2.6 on 2019-10-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    """Auto generated migration for default addition in age column."""

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
