"""Migration for adding order and task."""

# Generated by Django 2.2.6 on 2019-10-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for adding order and task."""

    initial = True

    dependencies = [
        ('client', '0002_femalemeasurements_malemeasurements'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(
                    choices=[('R', 'Recieved'), ('I', 'In Progress'), ('D', 'Delivered'), ('C', 'Closed')],
                    default='R',
                    max_length=1)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_amount', models.PositiveSmallIntegerField()),
                ('advance_payment_amount', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('date_recieved', models.DateField(auto_now_add=True)),
                ('order', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True, max_length=500, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(
                    choices=[('CR', 'Created'), ('I', 'In Progress'), ('C', 'Completed')],
                    default='CR',
                    max_length=2)),
                ('deadline', models.DateField()),
                ('employee', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='employee.Employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
